# Generated by Django 3.1.5 on 2021-01-16 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('nomdefamille', models.CharField(blank=True, max_length=200)),
                ('description_poste', models.TextField(default='Pas de description', max_length=300)),
                ('description_produit', models.TextField(default='Pas de produit', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('siret', models.IntegerField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(default='profilepic.png', upload_to='profilpic/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.ManyToManyField(blank=True, related_name='link', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
