# Generated by Django 3.1.5 on 2021-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210116_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='siret',
            field=models.IntegerField(blank=True),
        ),
    ]
